#name: adigna un nombre al flujo de trabajo
name: A workflow for my Hello World file
#El nombre del workflow se dara cada ves que ocurra el evento push
on: push

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"